spring: #???? ??
  profiles:
    active: local
  datasource: #???? 2?
    url: jdbc:mysql://jiwon-db.ckpdugluvawe.ap-northeast-2.rds.amazonaws.com:3306/mydb
    username: root
    password: wldnjsWkd1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: #???? 2?
    hibernate: #???? 4?
      ddl-auto: none #???? 6?
    properties: #???? 4?
      hibernate: #???? 6?
        # show_sql: true #???? 8?
        format_sql: true #???? 8?
logging.level: #???? ??
  org.hibernate.SQL: debug #???? 2?
  org.hibernate.type: trace
# org.hibernate.type: trace #???? 2?

jwt:
  secret: hello.world.ee.ff

